"use client";

/**
 * ExportPanel - "Export for Physician" control on /dashboard.
 *
 * Picks the export window (30 / 60 / 90 days, or a custom start/end range)
 * and downloads the clinical PDF generated by the FastAPI backend
 * (GET /api/py/export/report -> ReportLab + matplotlib). The browser saves
 * it as clinical_report_<end-date>.pdf.
 */
import { useMemo, useState } from "react";

import { useLowStim } from "@/lib/low-stim";

function isoDaysAgo(days: number): string {
  const d = new Date();
  d.setUTCDate(d.getUTCDate() - days + 1);
  return d.toISOString().slice(0, 10);
}

const PRESETS = [
  { days: 30, label: "Last 30 days" },
  { days: 60, label: "Last 60 days" },
  { days: 90, label: "Last 90 days" },
] as const;

export default function ExportPanel() {
  const { lowStim, t } = useLowStim();
  const [mode, setMode] = useState<"preset" | "custom">("preset");
  const [presetDays, setPresetDays] = useState<number>(30);
  const [start, setStart] = useState(isoDaysAgo(30));
  const [end, setEnd] = useState(isoDaysAgo(1));
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const border = { borderColor: lowStim ? "#fff" : "rgba(255,255,255,0.12)" } as const;
  const todayIso = useMemo(() => isoDaysAgo(1), []);

  const download = async () => {
    setBusy(true);
    setError(null);
    try {
      const params = new URLSearchParams();
      if (mode === "preset") {
        params.set("days", String(presetDays));
      } else {
        params.set("start", start);
        params.set("end", end);
      }
      const res = await fetch(`/api/py/export/report?${params.toString()}`, {
        cache: "no-store",
      });
      if (!res.ok) {
        let detail = String(res.status);
        try {
          const body = await res.json();
          if (body?.detail) detail = String(body.detail);
        } catch {
          /* non-JSON error */
        }
        throw new Error(detail);
      }
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `clinical_report_${mode === "preset" ? todayIso : end}.pdf`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      setTimeout(() => URL.revokeObjectURL(url), 4000);
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setBusy(false);
    }
  };

  return (
    <section className="mt-5 rounded-xl border p-4" style={border}>
      <p className="text-[10px] font-semibold uppercase tracking-wider opacity-60">
        {t("Export for physician")}
      </p>
      <p className="mt-1 text-[12px] leading-relaxed opacity-80">
        A standardized PDF with an executive summary, the Energy-Drain-vs-pain
        chart, your top symptom clusters and front/back body pain maps — ready
        to bring to an appointment.
      </p>

      <div className="mt-3 flex flex-wrap items-end gap-3">
        <div className="flex overflow-hidden rounded-md border text-[11px]" style={border}>
          {PRESETS.map((p) => (
            <button
              key={p.days}
              onClick={() => {
                setMode("preset");
                setPresetDays(p.days);
              }}
              className="px-2.5 py-1.5"
              style={{
                background:
                  mode === "preset" && presetDays === p.days
                    ? lowStim
                      ? "#fff"
                      : "#0ea5e9"
                    : "transparent",
                color:
                  mode === "preset" && presetDays === p.days
                    ? lowStim
                      ? "#000"
                      : "#fff"
                    : "inherit",
                fontWeight: mode === "preset" && presetDays === p.days ? 700 : 400,
              }}
              aria-pressed={mode === "preset" && presetDays === p.days}
            >
              {t(p.label)}
            </button>
          ))}
          <button
            onClick={() => setMode("custom")}
            className="px-2.5 py-1.5"
            style={{
              background: mode === "custom" ? (lowStim ? "#fff" : "#0ea5e9") : "transparent",
              color: mode === "custom" ? (lowStim ? "#000" : "#fff") : "inherit",
              fontWeight: mode === "custom" ? 700 : 400,
              borderLeft: `1px solid ${lowStim ? "#fff" : "rgba(255,255,255,0.12)"}`,
            }}
            aria-pressed={mode === "custom"}
          >
            {t("Custom range")}
          </button>
        </div>

        {mode === "custom" && (
          <div className="flex items-end gap-2 text-[11px]">
            <label>
              <span className="block text-[10px] uppercase tracking-wide opacity-60">from</span>
              <input
                type="date"
                value={start}
                max={end}
                onChange={(e) => setStart(e.target.value)}
                className="rounded border bg-transparent px-2 py-1"
                style={border}
              />
            </label>
            <label>
              <span className="block text-[10px] uppercase tracking-wide opacity-60">to</span>
              <input
                type="date"
                value={end}
                min={start}
                max={todayIso}
                onChange={(e) => setEnd(e.target.value)}
                className="rounded border bg-transparent px-2 py-1"
                style={border}
              />
            </label>
          </div>
        )}

        <button
          onClick={() => void download()}
          disabled={busy}
          className="ml-auto rounded-md bg-sky-600 px-4 py-2 text-xs font-semibold text-white hover:bg-sky-500 disabled:opacity-50"
          style={lowStim ? { border: "2px solid #fff" } : undefined}
        >
          {busy ? "Generating PDF…" : "⬇ Download clinical report (PDF)"}
        </button>
      </div>

      {error && (
        <p className="mt-2 rounded bg-red-950/70 px-3 py-2 text-xs text-red-300">
          Export failed: {error}
        </p>
      )}
      <p className="mt-2 text-[10px] leading-snug opacity-50">
        Contains only what was logged in the chosen window. The report is
        self-tracked data with model-based estimates — not a diagnosis.
      </p>
    </section>
  );
}
