/**
 * Plain-language aliases for anatomical terminology (Low Cognitive Load mode).
 *
 * Keys are the real English names used by BodyParts3D/FMA in the database.
 * Values are patient-friendly common names. Structures without an entry are
 * shown unchanged (they are already common words like "liver" or "heart").
 */
export const TERM_ALIASES: Record<string, string> = {
  // skull & spine
  "frontal bone": "forehead bone",
  "parietal bone": "upper-side skull bone",
  "right parietal bone": "upper-side skull bone (right)",
  "left parietal bone": "upper-side skull bone (left)",
  "temporal bone": "ear-area skull bone",
  "right temporal bone": "ear-area skull bone (right)",
  "left temporal bone": "ear-area skull bone (left)",
  "occipital bone": "back of skull",
  "sphenoid bone": "deep wing-like skull bone",
  ethmoid: "deep nose bone",
  "zygomatic bone": "cheekbone",
  "right zygomatic bone": "cheekbone (right)",
  "left zygomatic bone": "cheekbone (left)",
  maxilla: "upper jaw",
  "right maxilla": "upper jaw (right)",
  "left maxilla": "upper jaw (left)",
  "nasal bone": "nose bridge bone",
  "right nasal bone": "nose bridge bone (right)",
  "left nasal bone": "nose bridge bone (left)",
  "lacrimal bone": "tear-duct bone",
  "right lacrimal bone": "tear-duct bone (right)",
  "left lacrimal bone": "tear-duct bone (left)",
  "palatine bone": "roof-of-mouth bone",
  "right palatine bone": "roof-of-mouth bone (right)",
  "left palatine bone": "roof-of-mouth bone (left)",
  vomer: "lower nose-septum bone",
  mandible: "jawbone",
  "hyoid bone": "tongue-support bone",
  atlas: "top neck bone (head nodding)",
  axis: "second neck bone (head turning)",
  "third cervical vertebra": "third neck bone",
  "fourth cervical vertebra": "fourth neck bone",
  "fifth cervical vertebra": "fifth neck bone",
  "sixth cervical vertebra": "sixth neck bone",
  "seventh cervical vertebra": "seventh neck bone (base of neck)",
  "first thoracic vertebra": "first mid-back bone",
  "second thoracic vertebra": "second mid-back bone",
  "third thoracic vertebra": "third mid-back bone",
  "fourth thoracic vertebra": "fourth mid-back bone",
  "fifth thoracic vertebra": "fifth mid-back bone",
  "sixth thoracic vertebra": "sixth mid-back bone",
  "seventh thoracic vertebra": "seventh mid-back bone",
  "eighth thoracic vertebra": "eighth mid-back bone",
  "ninth thoracic vertebra": "ninth mid-back bone",
  "tenth thoracic vertebra": "tenth mid-back bone",
  "eleventh thoracic vertebra": "eleventh mid-back bone",
  "twelfth thoracic vertebra": "twelfth mid-back bone",
  "first lumbar vertebra": "first low-back bone",
  "second lumbar vertebra": "second low-back bone",
  "third lumbar vertebra": "third low-back bone",
  "fourth lumbar vertebra": "fourth low-back bone",
  "fifth lumbar vertebra": "fifth low-back bone",
  sacrum: "base of spine (tailbone area)",
  manubrium: "top of breastbone",
  "body of sternum": "middle of breastbone",
  "xiphoid process": "bottom tip of breastbone",
  // limbs
  clavicle: "collarbone",
  "right clavicle": "collarbone (right)",
  "left clavicle": "collarbone (left)",
  scapula: "shoulder blade",
  "right scapula": "shoulder blade (right)",
  "left scapula": "shoulder blade (left)",
  humerus: "upper arm bone",
  "right humerus": "upper arm bone (right)",
  "left humerus": "upper arm bone (left)",
  radius: "forearm bone (thumb side)",
  "right radius": "forearm bone, thumb side (right)",
  "left radius": "forearm bone, thumb side (left)",
  "right ulna": "forearm bone, little-finger side (right)",
  "left ulna": "forearm bone, little-finger side (left)",
  "hip bone": "pelvis bone",
  "right hip bone": "pelvis bone (right)",
  "left hip bone": "pelvis bone (left)",
  femur: "thigh bone",
  "right femur": "thigh bone (right)",
  "left femur": "thigh bone (left)",
  patella: "kneecap",
  "right patella": "kneecap (right)",
  "left patella": "kneecap (left)",
  "right tibia": "shin bone (right)",
  "left tibia": "shin bone (left)",
  "right fibula": "thin outer shin bone (right)",
  "left fibula": "thin outer shin bone (left)",
  // heart & vessels
  "wall of heart": "heart muscle shell",
  myocardium: "heart muscle",
  "tricuspid valve": "right-side heart valve",
  "mitral valve": "left-side heart valve",
  "pulmonary valve": "lung-artery valve",
  "right atrium": "upper-right heart chamber",
  "left atrium": "upper-left heart chamber",
  "right ventricle": "lower-right heart chamber",
  "left ventricle": "main pumping chamber",
  "ascending aorta": "main artery, upward stretch",
  "arch of aorta": "main artery, arch curve",
  "descending aorta": "main artery, downward stretch",
  "superior vena cava": "big vein from upper body",
  "inferior vena cava": "big vein from lower body",
  "pulmonary artery": "heart-to-lungs artery",
  "pulmonary vein": "lungs-to-heart vein",
  "right coronary artery": "heart's own artery (right)",
  "left coronary artery": "heart's own artery (left)",
  "coronary sinus": "heart's own collecting vein",
  "great cardiac vein": "heart's main draining vein",
  "middle cardiac vein": "heart's back draining vein",
  "small cardiac vein": "small heart vein",
  "right common carotid artery": "neck artery to head (right)",
  "left common carotid artery": "neck artery to head (left)",
  "brachiocephalic artery": "arm-and-head artery trunk",
  "brachiocephalic artery, nsn": "arm-and-head artery trunk",
  "right subclavian artery": "under-collarbone artery (right)",
  "left subclavian artery": "under-collarbone artery (left)",
  "right brachiocephalic vein": "upper-body vein (right)",
  "left brachiocephalic vein": "upper-body vein (left)",
  "right common iliac vein": "pelvis vein (right)",
  "left common iliac vein": "pelvis vein (left)",
  // airways & lungs
  "thyroid cartilage": "Adam's apple (voice box frame)",
  trachea: "windpipe",
  bronchus: "windpipe branches",
  "upper lobe of right lung": "right lung, top section",
  "middle lobe of lung": "right lung, middle section",
  "lower lobe of right lung": "right lung, bottom section",
  "upper lobe of left lung": "left lung, top section",
  "lower lobe of left lung": "left lung, bottom section",
  // digestive
  esophagus: "food pipe",
  duodenum: "first part of small bowel",
  jejunum: "middle part of small bowel",
  ileum: "last part of small bowel",
  "large intestine": "bowel frame",
  colon: "large bowel",
  rectum: "bowel exit pouch",
  gallbladder: "bile storage bag",
  "pancreas, nsn": "pancreas",
  // urinary & reproductive
  "right kidney": "kidney (right)",
  "left kidney": "kidney (left)",
  "right ureter": "kidney-drain tube (right)",
  "left ureter": "kidney-drain tube (left)",
  "urinary bladder": "bladder",
  urethra: "bladder outlet tube",
  "right testis": "testicle (right)",
  "left testis": "testicle (left)",
  // brain & nerves
  "cerebral hemisphere": "main brain (thinking part)",
  "corpus callosum": "brain bridge (links halves)",
  "right caudate nucleus": "movement-control center (right)",
  "left caudate nucleus": "movement-control center (left)",
  "right putamen": "movement-control center (right)",
  "left putamen": "movement-control center (left)",
  "right globus pallidus": "movement-control center (right)",
  "left globus pallidus": "movement-control center (left)",
  "right amygdala": "fear/emotion center (right)",
  "left amygdala": "fear/emotion center (left)",
  "right hippocampus": "memory center (right)",
  "left hippocampus": "memory center (left)",
  thalamus: "brain relay station",
  "hypothalamus, nsn": "body-control hub (hormones, appetite)",
  hypothalamus: "body-control hub (hormones, appetite)",
  epithalamus: "pineal area (sleep timing)",
  "right fornix of forebrain": "memory wiring (right)",
  "left fornix of forebrain": "memory wiring (left)",
  "midbrain, nsn": "mid-brain relay",
  pons: "brainstem relay (breathing, sleep)",
  "medulla oblongata": "life-support brainstem (heart rate, breathing)",
  cerebellum: "balance & coordination center",
  "right optic nerve": "eye nerve (right)",
  "left optic nerve": "eye nerve (left)",
  // muscles
  diaphragm: "main breathing muscle",
  "right infraspinatus muscle": "shoulder blade muscle (right)",
  "left infraspinatus muscle": "shoulder blade muscle (left)",
  "external intercostal muscle": "rib breathing muscles (outer)",
  "internal intercostal muscle": "rib breathing muscles (inner)",
  "innermost intercostal muscle": "rib breathing muscles (deepest)",
  "right rectus abdominis": "stomach muscles (right)",
  "left rectus abdominis": "stomach muscles (left)",
  "right sternothyroid": "voice-box muscle (right)",
  "left sternothyroid": "voice-box muscle (left)",
  "right sternohyoid": "swallowing muscle (right)",
  "left sternohyoid": "swallowing muscle (left)",
  "right thyrohyoid": "swallowing muscle (right)",
  "left thyrohyoid": "swallowing muscle (left)",
  // endocrine & lymphatic
  "adrenal gland": "stress gland",
  "right adrenal gland": "stress gland (right)",
  "left adrenal gland": "stress gland (left)",
  "pituitary gland": "master hormone gland",
  thymus: "immune-training gland",
  "right lobe of thymus": "immune gland (right lobe)",
  "left lobe of thymus": "immune gland (left lobe)",
  spleen: "blood-filter & immune organ",
};

/** Returns the plain-language alias when enabled, else the original term. */
export function aliasTerm(name: string, enabled: boolean): string {
  if (!enabled) return name;
  return TERM_ALIASES[name.toLowerCase()] ?? name;
}
